services:
  pupper-mysql:
    image: mysql:lts
    healthcheck:
      test: mysqladmin ping -proot
    environment:
      MYSQL_ROOT_PASSWORD: root # This is just an example, not intended to be a production configuration
      MYSQL_DATABASE: pupper_example
    ports:
      - "3306:3306"
    restart: always

